version: '3.8'
services:

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app-server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db
  
  app-ui:
    image: nginx:alpine
    volumes:
      - ./ui/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8001:8001"

volumes:
  mongo_data:
